### ISSUE TITLE
Status stuck in "Queued", error message not readable

### ISSUE THREAD

**Issue by dpshee** [Microsoft/ConversationLearner-Samples#203]
When creating and training dialogs within an app the "Status" field on the left side of the GUI is constantly "Queued".  I see a red error icon flash next to it very briefly intermittently, but never long enough for me to click on and capture the actual error.

Since none of my apps ever complete their training I am unable to publish any of the apps I have built.  Is there a way to force training or even see details behind what is causing this error?

Viewing UI in Chrome

**Comment by dpshee** [comment]
Was able to finally capture the error message...
Refreshing does nothing to help get the app out of the "Queued" state

![errorcap](https://user-images.githubusercontent.com/3695862/40496833-b3023826-5f48-11e8-8fc3-b047ed4930e5.PNG)

**Comment by mattmazzola** [comment]
Hmm... yes, that blue "Refresh" text/button only retries the polling but doesn't actually force or trigger re-training because we don't want people spamming that and causing excessive load on the system.

We are considering opening up API to do this, but for now you should be able to submit a new request for training by doing any operation that would trigger it normally and this might fix it.  Example is to create a dummy entity that you don't plan to use.

It's very odd that it is stuck in the Queue phase.  The status should either resolve to failed or completed and that's what the polling waits for.  I will try to investigate.

Also, do you have anything particular about your app?
Number of actions?
Has there been a successful training previously or was it always stuck in Queued?

**Comment by amthomas46** [comment]
I'm having this same issue. None of my apps - from hello world to pizza will exit the "Queue" phase, and I get the quickly disappearing error. Everything was working fine last night when I was testing. If I add a train dialog to HelloWorld, most basic, it just queues. Same if I add to any other apps.

**Comment by mattmazzola** [comment]
We've confirmed the issue queuing right now and are investigating.

**Comment by mattmazzola** [comment]
Service is up and running. We're still investigating the root cause to prevent it happening again.

Let us know if you see further issues with training
